package com.juan.spidergames.api.kakuro;

import java.util.List;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

import com.juan.spidergames.enums.KakuroStatus;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiModelProperty.AccessMode;

@ApiModel(description = "Transfer object for a single Kakuro")
public class KakuroDTO {
	
	@ApiModelProperty(value = "Mongo DB autogenerated Id", accessMode = AccessMode.READ_ONLY)
	private String id;

	@Min(3)
	@Max(14)
	@ApiModelProperty(value = "Kakuro rows count", required = true)
	private Integer height;

	@Min(3)
	@Max(14)
	@ApiModelProperty(value = "Kakuro columns count", required = true)
	private Integer width;
	
	@ApiModelProperty(value = "Must match enum", required = true)
	private KakuroStatus status;
	
	@ApiModelProperty()
	private List<List<CellDTO>>  cells;

}
