package com.juan.spidergames.api.kakuro;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import com.juan.spidergames.enums.Difficulty;
import com.juan.spidergames.enums.KakuroStatus;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiModelProperty.AccessMode;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ApiModel(description = "Transfer object for a single Kakuro")
public class KakuroDTO {
	
	@ApiModelProperty(value = "Mongo DB autogenerated Id", accessMode = AccessMode.READ_ONLY)
	private String id;
	
	@ApiModelProperty
	private Difficulty difficulty;

	@Min(3)
	@Max(14)
	@NotNull
	@ApiModelProperty(value = "Kakuro rows count", required = true)
	private Integer height;

	@Min(3)
	@Max(14)
	@NotNull
	@ApiModelProperty(value = "Kakuro columns count", required = true)
	private Integer width;
	
	@ApiModelProperty(value = "Must match enum", required = true)
	private KakuroStatus status;
	
	@NotNull
	@ApiModelProperty()
	private List<List<@Valid KakuroCellDTO>> grid;

}
